# This is a workflow to help you setup Bridgecrew in github code scanning 
# Additional information can be found here: https://docs.bridgecrew.io/docs/setup-github-code-scanning
#
name: Bridgecrew

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "bridgecrew"
   bridgecrew:
    runs-on: ubuntu-latest
    permissions:
      actions: [ write, read ]
      contents: write
      security-events: write
    
    steps:
    - name: Run Bridgecrew 
      uses: actions/checkout@v2
    
    - name:  
      id: Bridgecrew
      uses: bridgecrewio/bridgecrew-action@master
      with:
        api-key: ${{ secrets.API_KEY }}
        soft_fail: true
        #sarif_file: results.sarif
    - name: Expose report
      uses: actions/upload-artifact@v2
      with:
        name: SARIF results
        path: results.sarif
    # Uploads results.sarif to GitHub repository using the upload-sarif action
    # - uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     # Path to SARIF file relative to the root of the repository
    #     sarif_file: results.sarif

    #- name: Checkout repo
    #  uses: actions/checkout@v2
    #  with:
    #  fetch-depth: 0
    - name: Run yor action
      uses: bridgecrewio/yor-action@main
      with:
        version: 0.1.129
      #directory: path/to/iac
      #skip_directory: test
        tags: git_modifiers,git_commit,git_repository,yor_trace
